### ISSUE TITLE
typo in ec2-termination

### ISSUE THREAD

**Issue by AstroTom** [miglen/aws#1]
in https://github.com/miglen/aws/blob/master/ec2/run-script-on-ec2-instance-termination.md you have "ls" instead of "ln" for the link command.

It should be:

> ln -s /etc/ec2-termination /etc/rc0.d/S01ec2-termination

**Comment by miglen** [comment]
Thanks @AstroTom  fixed in https://github.com/miglen/aws/commit/036380e18e6e33399ad2fa40f9af35225621bae9
